sinceNow: true
filters:
- rules:
    involvedObject.kind: Job
    involvedObject.name: "^*.fail"
    reason: BackoffLimitExceeded
  errorRules:
    # In this specific case, we want to mark this event ALWAYS as an error
    type: .*

webhooks:
  - url: https://hook.notify17.net/api/template/q5IeIiOX6FyH081Db_CmBCcebib6YITs6mFcyJw1PRQ